version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spotify-postgres-db
    environment:
      POSTGRES_USER: spotifyuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: spotify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: